---
ansible_connection: local

namespace: jacob-iot-temp

deploy:
  NAME: "{{ app_name }}"

build:
  NAME: "{{ app_name }}"
  S2I_BASE_IMAGE: "openjdk18-openshift:latest"
  GIT_SOURCE_REF: labs-concepts
  GIT_SOURCE_URI: "https://github.com/jacobsee/industry-4.0-demo.git"
  GIT_SOURCE_CONTEXT_DIR: bridge

openshift_cluster_content:
- object: app-builds
  content:
  - name: "{{ app_name }}-build"
    template: "templates/app-build.yml"
    params_from_vars: "{{ build }}"
    namespace: "{{ namespace }}"
    tags:
    - app-build
# - object: app-deploy
#   content:
#   - name: "{{ app_name }}-deploy"
#     template: "templates/app-deploy.yml"
#     params_from_vars: "{{ deploy }}"
#     namespace: "{{ namespace }}"
#     tags:
#     - app-deploy