---
ansible_connection: local

repo_name: "{{ app_name }}"
openshift_url: https://{{ console_domain | default('console') }}.{{ base_openshift_url }}:443
namespace: jacob-iot-temp

deploy:
  NAME: "{{ app_name }}"


build:
  NAME: "{{ app_name }}"
  S2I_BASE_IMAGE: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
  GIT_SOURCE_REF: labs-concepts
  GIT_SOURCE_URI: https://github.com/jacobsee/industry-4.0-demo
  PIPELINE_SOURCE_REPOSITORY_URL: https://github.com/jacobsee/industry-4.0-demo
  PIPELINE_SOURCE_REPOSITORY_REF: labs-concepts

openshift_cluster_content:
- object: app-builds
  content:
  - name: "{{ app_name }}-build"
    template: "templates/app-build.yml"
    params_from_vars: "{{ build }}"
    namespace: "{{ jacob-iot-temp }}"
    tags:
    - app-build
- object: app-deploy
  content:
  - name: "{{ app_name }}-deploy"
    template: "templates/app-deploy.yml"
    params_from_vars: "{{ deploy }}"
    namespace: "{{ jacob-iot-temp }}"
    tags:
    - app-deploy