---
kind: Template
apiVersion: v1
metadata:
  name: s2i-app-build
  annotations:
    openshift.io/display-name: S2I App Build Template
    description: S2I binary build config to create an image with your app baked in.
    iconClass: fa-cube
    tags: s2i
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: "${NAME}"
      app: "${NAME}"
    name: "${NAME}"
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: "${NAME}"
      name: "${NAME}"
      type: image
      app: "${NAME}"
    name: "${NAME}"
  spec:
    nodeSelector:
    output:
      to:
        kind: ImageStreamTag
        name: "${NAME}:latest"
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: "${GIT_SOURCE_CONTEXT_DIR}"
      git:
        ref: "${GIT_SOURCE_REF}"
        uri: "${GIT_SOURCE_URI}"
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: "${S2I_BASE_IMAGE}"
          namespace: openshift
      type: Source
  status:
    lastVersion: 1
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all objects and the resulting imagestream.
  required: true
  value: s2i-app
- name: GIT_SOURCE_URI
  displayName: Source Code Git Repository URL
  description: The URL of the repository with your source code to be built.
  required: true
- name: GIT_SOURCE_REF
  displayName: Source Code Git Reference
  description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default (master) branch.
  value: master
- name: GIT_SOURCE_SECRET
  displayName: Secret for git repository
  description: The name of the OCP secret that has credentials for the pipeline git
    repository
- name: GIT_SOURCE_CONTEXT_DIR
  displayName: Source Code Git Context Directory
  description: Set this to the directory where the app source code is if not using the
    default root directory
  value: git-secret
- name: GENERIC_WEBHOOK
  displayName: Generic Webook
  description: OCP secret string to configure a Generic webhook
  generate: expression
  from: "[a-zA-Z0-9]{20}"
- name: GITHUB_WEBHOOK
  displayName: Github Webook
  description: OCP secret string to configure a Github webhook
  generate: expression
  from: "[a-zA-Z0-9]{20}"
- name: GITLAB_WEBHOOK
  displayName: Gitlab Webook
  description: OCP secret string to configure a Gitlab webhook
  generate: expression
  from: "[a-zA-Z0-9]{20}"
- name: BITBUCKET_WEBHOOK_PR
  displayName: Bitbucket Webook for PR Builds
  description: OCP secret string to configure a Bitbucket webhook
  generate: expression
  from: "[a-zA-Z0-9]{20}"
- name: GENERIC_WEBHOOK_PR
  displayName: Generic Webook for PR Builds
  description: OCP secret string to configure a Generic webhook
  generate: expression
  from: "[a-zA-Z0-9]{20}"
- name: GITHUB_WEBHOOK_PR
  displayName: Github Webook for PR Builds
  description: OCP secret string to configure a Github webhook
  generate: expression
  from: "[a-zA-Z0-9]{20}"
- name: GITLAB_WEBHOOK_PR
  displayName: Gitlab Webook for PR Builds
  description: OCP secret string to configure a Gitlab webhook
  generate: expression
  from: "[a-zA-Z0-9]{20}"
- name: S2I_BASE_IMAGE
  displayName: S2I Base Image for Application
  description: The base image for building the Application with S2I, including image
    tag
  required: true
  value: redhat-openjdk18-openshift:latest